name: Feature
description: An enhancement or feature
title: "[Feature]: "
labels: ["triage", "feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A step-by-step description of the suggested feature/enhancement.
      placeholder: On the user page, you should be able to...
    validations:
      required: true
  - type: textarea
    id: acceptanceCriteria
    attributes:
      label: Acceptance Criteria
      description: What are the things that must be achieved for your ticket to be considered complete.
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        | Please include any screenshots which would help demonstrate the steps
        and point out which parts the feature is related to
  - type: textarea
    id: links
    attributes:
      label: Links
      description: Place links to supporting docs here. e.g. Figma
      value: >
        | [`FIGMA LINK`](LINK_HERE)
  - type: textarea
    id: images
    attributes:
      label: Images
      description: Paste images or image urls
      value: "![image](URL_HERE)"
