services:

  frontend:
    image: hngdevops/nextjs-boilerplate:prod
    ports:
      - 3000:3000
    volumes:
      - ../../.env:/app/.env

  # next-prod-frontend-2:
  #   build:
  #     context: ../../
  #     dockerfile: docker/prod/Dockerfile
  #   ports:
  #     - 3030:3000
  #   restart: always
