services:
  prod-frontend-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always

  prod-frontend-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:3000
    restart: always
