import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import Navbar from "~/components/layouts/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex min-h-screen bg-stroke-200 antialiased ${inter.className}`}
      >
        <div className="flex-auto">
          <Navbar />
          <div className="p-[30px]">{children}</div>
        </div>
      </body>
    </html>
  );
}
