import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Layout from "~/components/layouts";
import { Toaster } from "~/components/ui/toaster";

import "./globals.css";
import "~/components/layouts/homepage/styles/styles.css";

import Providers from "~/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
