services:
  
  frontend:
    image: hngdevops/nextjs-boilerplate:staging
    ports:
      - 3200:3000
    volumes:
      - ../../.env:/app/.env

  # next-staging-frontend-2:
  #   build:
  #     context: ../../
  #     dockerfile: docker/staging/Dockerfile
  #   ports:
  #     - 3230:3000
  #   restart: alwaysraven@frontend:/home/nextjs/staging/hng_boilerplate_nextjs/docker/staging$
