import "../globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import SubscriptionAndPlan from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SubscriptionAndPlan />
        {children}
      </body>
    </html>
  );
}
