name: Build and Upload

on:
  push:
    branches: [staging, main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "20"

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install dependencies
      run: pnpm install

    - name: Build Next.js application
      run: pnpm build

    - name: Archive production artifacts
      run: tar -czf boilerplate.tar.gz .next public

    - name: Upload production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: boilerplate-build
        path: boilerplate.tar.gz

    - name: Delete zip file
      run: rm -f boilerplate.tar.gz
