name: Report Coverage for PR

on:
  workflow_run:
    workflows: ["Test for PR"]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: "Report Coverage"
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
